namespace ModKit.Core;

public static class WorkspaceInitializer
{

    private static readonly string[] Refs =
    {
        "BepInEx.dll", "0Harmony.dll",
        "Assembly-CSharp.dll", "Assembly-CSharp-firstpass.dll",
        "Blocksters.MathLib.dll", "BehaviourLibraryBuild.dll",
        "Unity.InputSystem.dll", "com.rlabrecque.steamworks.net.dll",
        "UnityEngine.dll", "UnityEngine.CoreModule.dll", "UnityEngine.IMGUIModule.dll",
        "UnityEngine.TextRenderingModule.dll", "UnityEngine.ImageConversionModule.dll",
        "UnityEngine.InputLegacyModule.dll", "UnityEngine.PhysicsModule.dll",
        "BlockStoryCore.dll",
    };

    public static void Init(string workspaceDir, string gameDir, Action<string>? log = null)
    {
        string refs = Path.Combine(workspaceDir, "refs");
        string mods = Path.Combine(workspaceDir, "mods");
        Directory.CreateDirectory(refs);
        Directory.CreateDirectory(mods);

        string[] sources =
        {
            GamePaths.ManagedDir(gameDir),
            Path.Combine(gameDir, "BepInEx", "core"),
            GamePaths.PluginsDir(gameDir),
            gameDir,
        };

        int missing = 0;
        foreach (string name in Refs)
        {
            string? src = sources.Select(s => Path.Combine(s, name)).FirstOrDefault(File.Exists);
            if (src != null) { File.Copy(src, Path.Combine(refs, name), true); log?.Invoke("  ref  " + name); }
            else { missing++; log?.Invoke("  MISSING  " + name + "  (build the mods + install Core first?)"); }
        }

        File.WriteAllText(Path.Combine(mods, "Directory.Build.props"), DirectoryBuildProps());
        log?.Invoke(missing == 0
            ? "Workspace ready: " + workspaceDir
            : $"Workspace set up with {missing} missing ref(s) — install the base mod pack into the game first.");
    }

    public static bool IsInitialized(string workspaceDir)
        => File.Exists(Path.Combine(workspaceDir, "mods", "Directory.Build.props"))
           && File.Exists(Path.Combine(workspaceDir, "refs", "BlockStoryCore.dll"));

    private static string DirectoryBuildProps()
    {
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("<Project>");
        sb.AppendLine("  <!-- Shared settings + references for every mod in this workspace (generated by Block Story Mod Kit). -->");
        sb.AppendLine("  <PropertyGroup>");
        sb.AppendLine("    <TargetFramework>netstandard2.1</TargetFramework>");
        sb.AppendLine("    <LangVersion>latest</LangVersion>");
        sb.AppendLine("    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>");
        sb.AppendLine("    <Configuration>Release</Configuration>");
        sb.AppendLine("    <DebugType>none</DebugType>");
        sb.AppendLine("  </PropertyGroup>");
        sb.AppendLine("  <ItemGroup>");
        foreach (string r in Refs)
        {
            string asm = Path.GetFileNameWithoutExtension(r);
            sb.AppendLine($"    <Reference Include=\"{asm}\"><HintPath>$(MSBuildThisFileDirectory)../refs/{r}</HintPath><Private>false</Private></Reference>");
        }
        sb.AppendLine("  </ItemGroup>");
        sb.AppendLine("</Project>");
        return sb.ToString();
    }
}
